---
- hosts: all
  tasks:
    - name: checkout private repo
      git:
        repo: https://github.com/lileddie/netbox.git
        dest: /var/tmp/
        version: master
        accept_hostkey: yes
    - name: install newest version of nginx
      apt: name=nginx state=latest
      become: yes
    - name: copy netbox config files
      copy:
        src: /var/tmp/netbox/nginxConfig.cfg
        dest: /etc/nginx/sites-available/netbox.cfg
      become: yes
    - name: create sym link
      file:
        src: /etc/nginx/sites-available/netbox.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
    - name: start nginx
      service:
        name: nginx
        state: start
      become: yes
    - name: remove cloned repo
      file:
        path: /var/tmp/netbox
        state: absent
      become: yes
